### ISSUE TITLE
Handle various authentications schemes

### ISSUE THREAD

**Issue by sckott** [ropensci/solr#21]
I think we just handle an API key passed in the url for now...

**Comment by areuser** [comment]
Access management is hardly provided by the solr library. One could, however, question whether the solr  package should be able to handle authentication schemes. 

In the current situation solr is more or less access management agnostic. 
This provides the ability to use your custom access management implementation and apply that to solr.  Just an example. Your credentials or token can be added as a header to the solr_search request by :

```
baseUrl <- "..solr server.."
callopts <- httr::add_headers(username=your_name,password=your_pass)
response <- solr_search(q='*:*', callopts=callopts,base=baseUrl)
```

**Comment by sckott** [comment]
I have been thinking the same that perhaps this client shouldn't handle authentication. As you point out users can pass in authentication to `httr`. I was looking around to see if there is any auth built into Solr, but it appears there is not, correct?

**Comment by areuser** [comment]
Because solr is focused on enterprise search it's access management agnostic. Furthermore custom access management implementations typically introduce hairball architectures that are hard to unwind. 

My advice would be to start using the basic features of the container of solr to configure your requirements. If these features turn out to be too limited or too hard to configure you could always move to a more mature identity & access management solution like OpenAM.  

Just let me know if you have more questions on this.

**Comment by sckott** [comment]
@areuser Thanks for the info. Okay, so best that `solr` doesn't deal with auth at all then, other than allowing users to pass in options to `httr`.
